Feature contact validation
eduardosancho/setup_and_mobile_version_skeleton pull request #14
Opened 2021-12-16 04:00 UTC by eduardosancho

What was done in this PR:

-Remove 'required' property from form elements.
-Use javascript to validate the information inserted by the user.

-[x] Name field cannot be empty
-[x] Email field cannot be empty
-[x] Email field cannot have capital letters
-[x] Email field must have a valid email address. (following syntax abc@domain.com)

2021-12-16 07:00 UTC, oxenprogrammer requested changes
Hi @eduardosancho, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 07:00 UTC, oxenprogrammer commented on index.html
> +                    <button type="submit" class="full" id="submit-form">Start collaboration</button>
**Changes Required**
- [x] Please let us also try and validate `textarea` field. Apparently one can submit the form without any message.

2021-12-16 07:00 UTC, oxenprogrammer commented on index.html
> +                    <button type="submit" class="full" id="submit-form">Start collaboration</button>
-  [x] Also your error message should be closer to the submit button has described in the requirements.

2021-12-18 04:33 UTC, eduardosancho commented
It seems linters are not working on GitHub right now.
I ran the checks locally and these were the results, everything passed fine.

![image](https://user-images.githubusercontent.com/53308506/146628974-17a4c582-e1a7-4ed1-ae47-d4eb76f284cc.png)

2021-12-18 04:54 UTC, Cathella approved these changes
## 🟢 Status: Approved 🎉💪🏻

### Hi @team ✋🏻, 

You have done well implementing the requested changes 💪🏻, You form now submits and is well validated, Kudos to you 🎉🍾!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 02:18 UTC, merged